# IBM Cognitive Class - Python for Data Science
IBM: PY0101EN - Python notebooks


In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [13]:
def Pink():
    global claimedsales
    claimedsales = '47 million' 
    return claimedsales

Pink()

'47 million'

In [14]:
x=1

if(x!=1):

    print('Hello')

else:

    print('Hi')

print('Mike')

Hi
Mike


In [15]:
A = ['1','2','3']

for a in A:

    print(2*a)

11
22
33


In [24]:
def Delta(x):
    if x==0:
        y=1;
    else:
        y=0;
    return(y)

In [29]:
Delta(0)

1

In [40]:
file1 = open("/C:\Users\Ali\Documents/galaxy.txt","r")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 3-4: truncated \UXXXXXXXX escape (1820569141.py, line 1)

In [1]:
file1.readline()

NameError: name 'file1' is not defined

In [43]:
import pandas as banana

df=banana.DataFrame({'a':[11,21,31],'b':[21,22,23]})

df.head()

a   b
0  11  21
1  21  22
2  31  23

In [44]:
df=pd.DataFrame({'a':[1,2,1],'b':[1,1,1]})
df['a']==1

0     True
1    False
2     True
Name: a, dtype: bool

In [47]:
new1 = np.array([1,-1])*np.array([1,1])
new1

array([ 1, -1])

In [48]:
new2 = np.dot(np.array([1,-1]),np.array([1,1]))
new2

0

In [49]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.dot(A,B)

ValueError: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [12]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

np.dot(a,b)

0

In [7]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [8]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])

In [16]:
A = ['1','2','3']

for a in A:

    print(3*a)

111
222
333


In [18]:
a=np.array([1,2,3,1,1])

a*10

array([10, 20, 30, 10, 10])

In [22]:
var = '01234567'
print(var[::2])

0246


In [23]:
3+2*2

7

In [24]:
int(3.2)

3

In [25]:
A='1234567'
A[1::2]

'246'

In [26]:
Name="Michael Jackson"
Name.find('el')

5

In [27]:
tuple1=("A","B","C" )
tuple1[-1]

'C'

In [28]:
A=((11,12),[21,22])
A[1]

[21, 22]

In [29]:
A=((11,12),[21,22])
A[0][1]

12

In [30]:
'1,2,3,4'.split(',')

['1', '2', '3', '4']

In [32]:
A=[1,'a']
B=[2,1,'d']
A+B

[1, 'a', 2, 1, 'd']

In [38]:
V={'A','B','C'}
V.add('C')
V

{'A', 'B', 'C'}

In [42]:
for n in range(3):
    print(n)

0
1
2


In [43]:
for n in range(3):

    print(n+1)

1
2
3


In [44]:
A=['1','2','3']

for a in A:

    print(2*a)

11
22
33


In [46]:
def Add(x,y):

    z=y+x

    return(y)

In [48]:
class Points(object):
    def __init__(self,x,y):
        self.x=x
        self.y=y
    def print_point(self):
        print('x=',self.x,'y=',self.y)

In [49]:
class Points(object):

    def __init__(self,x,y):

        self.x=x

        self.y=y

    def print_point(self):

        print('x=',self.x,' y=',self.y)

p1=Points(1,2)

p1.print_point()

x= 1  y= 2


In [50]:
class Points(object):

    def __init__(self,x,y):

        self.x=x

        self.y=y

    def print_point(self):

        print('x=',self.x,' y=',self.y)

p2=Points(1,2)

p2.x=2

p2.print_point()

x= 2  y= 2
